import React from 'react';
import './TSR.css';
import commonkeys from '../images/commonkeys.png';

const CommonKeys = () => {
    return (
        <div className="tsr-method-page">
            <aside className="toc">
                <nav>
                    <ul>
                        <li><a href="#abstract">Abstract</a></li>
                        <li><a href="#tutorial">Tutorial</a></li>
                        <li><a href="#source-code">Source Code</a></li>
                    </ul>
                </nav>
            </aside>

            <div className="content-tsr">
                <section id="abstract" className="section-tsr abstract-section">
                    <h2 className="section-title">Common Keys</h2>
                    <p className="section-paragraph">
                    </p>
                    Lets understand common keys calculation with an example.
                    <p>
                        A given dataset has two protein classes: X and Y. There are three proteins—X1, X2 and X3—in Class A, whereas there are two proteins—Y1 and Y2—in Class Y. The sets of distinct TSR keys for each protein in the dataset are shown in Figure a. The key occurrences (frequencies) for each protein can be found in Figure b. Figure c shows “Specific” TSR keys of Class X and Class Y and “Common” TSR keys of the dataset. “common” TSR keys for Class X, Class Y and the dataset are illustrated in Figure d, e and f, respectively. “common” keys of the dataset are the intersection between “common” keys of Class X and “common” keys of Class Y. Figure g reveals how “Distinct_Common”, “Total_Common”, “Distinct” and “Total” keys are calculated. “specific” TSR keys for Class X and Class Y are shown in Figure h. “specific” TSR keys of Class X (Y) is a subset of “Specific” TSR keys of Class X (Y).
                    </p>
                    <div className="protein-illustration">
                        <img src={commonkeys} alt="Common Keys Illustration" className="mirror-image" />
                    </div>
                </section>

                {/* Tutorial Section with New Styles */}
                <section id="tutorial" className="section-tsr tutorial-section">
                    <h2 className="tutorial-title">Tutorial</h2>

                    {/* Installation Section */}
                    <h3 className="step-title">Installation</h3>
                    <p>To use the Common Keys package, follow the steps below to clone the repository and install the necessary dependencies:</p>
                    <ol className="tutorial-steps">
                        <li className="tutorial-step-item">
                            <span className="step-title">Clone the repository:</span>
                            <div className="code-block">
                                <code>
                                    git clone https://github.com/KrishnaRauniyar/Nucleotide_Analysis.git <br />
                                    cd common_key_package
                                </code>
                            </div>
                        </li>
                        <li className="tutorial-step-item">
                            <span className="step-title">Create a virtual environment and activate it:</span>
                            <div className="code-block">
                                <code>
                                    python3 -m venv tsrenv<br />
                                    source tsrenv/bin/activate  # Mac/Linux<br />
                                    tsrenv\Scripts\activate  # Windows
                                </code>
                            </div>
                        </li>
                        <li className="tutorial-step-item">
                            <span className="step-title">Install the required dependencies:</span>
                            <div className="code-block">
                                <code>pip install -r requirements.txt</code>
                            </div>
                        </li>
                    </ol>

                    {/* Usage Section */}
                    <h3 className="step-title">Usage</h3>
                    <p>Once installed, you can use the following command for common keys calculation.</p>

                    <h4 className="step-title">Generate Keys and Triplets</h4>
                    <div className="code-block">
                        <code>
                            python common_keys.py --path input_dir
                        </code>
                    </div>
                    <p>The <strong>input_dir</strong> is a directory which holds the input triplet files. The common keys will be calculated between all the triplet files generated by the key_triplets TSR package. You can give the direct path to the key_triplet files directory in the TSR package or make a new directory and place all the files in it.</p>

                    <h4 className="step-title">CSV file information as output (common_keys.csv)</h4>
                    <div className="code-block">
                        <code>
                            <div className="table-container">
                                <table>
                                    <thead>
                                        <tr>
                                            <th>fileName</th>
                                            <th>total_keys</th>
                                            <th>common_keys</th>
                                            <th>sum_common_keys_freq</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        <tr>
                                            <td>1_1TSR_E_DT</td>
                                            <td>4</td>
                                            <td>0</td>
                                            <td>0</td>
                                        </tr>
                                        <tr>
                                            <td>1_2AC0_E_DC</td>
                                            <td>1</td>
                                            <td>0</td>
                                            <td>0</td>
                                        </tr>
                                    </tbody>
                                </table>
                            </div>
                        </code>
                    </div>

                    <p>File name are all the triplets files in the input_dir. We have total_keys, common_keys and sum_common_keys_freq which contains total number of keys in each triplet files, common keys in all the triplet files and sum of all the triplet keys which are common respectively.</p>
                </section>

                <section id="source-code" className="section-tsr source-code-section">
                    <h2 className="section-title">Source Code</h2>
                    <p className="section-paragraph">
                        The full source code for the Common Keys package is available on GitHub. You can explore, contribute, or fork the repository using the following link:
                    </p>
                    <div className="code-block">
                        <code>
                            <a href="https://github.com/KrishnaRauniyar/Nucleotide_Analysis.git" target="_blank" rel="noopener noreferrer" className="source-code-link">
                                GitHub Repository: https://github.com/KrishnaRauniyar/Nucleotide_Analysis.git
                            </a>
                        </code>
                    </div>
                    <p className="section-paragraph">
                        Feel free to review the README.md file for more detailed instructions, and don’t hesitate to open issues or pull requests to help improve the project.
                    </p>
                </section>
            </div>
        </div>
    );
}

export default CommonKeys;

